version: '3'
services:

  db:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123ewqasd
      - POSTGRES_USER=dev
      - POSTGRES_DB=sample
    ports:
      - "5432:5432"

volumes:
  pg_data:

